---
- name: Include user settings
  ansible.builtin.include_tasks:
    file: user.yml

- name: Include reconfigure satellite tasks
  ansible.builtin.include_tasks:
    file: reconfigure.yml

- name: Include LeCertificate for satellite
  when: lb1152_hol_satellite_reconfigure_lecertificate | bool
  ansible.builtin.include_tasks:
    file: lecertificate.yml

- name: Include RHSM subscription
  when: "lb1152_hol_satellite_reconfigure_subscription_type == 'rhsm'"
  ansible.builtin.include_tasks:
    file: rhsm.yml

- name: Download latest iop advisor image
  when: lb1152_hol_satellite_reconfigure_iop_download_new_image | bool
  ansible.builtin.include_tasks:
    file: iop_advisor_image.yml
