---
- name: Register Nodes to RHSM
  ansible.builtin.command:
    cmd: "{{ item }}"
  loop:
    - subscription-manager remove --all
    - subscription-manager clean

- name: Find RHUI repository files
  find:
    paths: /etc/yum.repos.d
    recurse: no
    patterns:
    - 'redhat-rhui*.repo'
    - 'redhat-rhui*.repo.*'

  register: r_find_repos

- name: Remove current RHUI repository files
  file:
    path: "{{ file.path }}"
    state: absent
  loop: "{{ r_find_repos.files }}"
  loop_control:
    loop_var: file
    label: "{{ file.path }}"
  ignore_errors: true

- name: Register Nodes to RHSM
  ansible.builtin.command: >-
    subscription-manager register
    --org "{{ lb1152_hol_satellite_reconfigure_sat_org }}"
    --activationkey "{{ lb1152_hol_satellite_reconfigure_sat_activation_key }}"

- name: Register with Red Hat Insights
  when: lb1152_hol_satellite_reconfigure_insights_org
  ansible.builtin.command: >-
    rhc connect
    -o {{ lb1152_hol_satellite_reconfigure_insights_org }}
    -a {{ lb1152_hol_satellite_reconfigure_insights_activation_key }}
