---
- name: Register node with Red Hat Insights
  ansible.builtin.command: >-
    rhc connect
    -o {{ lb1152_hol_node_config_insights_org }}
    -a {{ lb1152_hol_node_config_insights_activation_key }}

- name: Run insights-client to generate config files
  ansible.builtin.command: insights-client --collector malware-detection

- name: Configure insight malware detection - 1
  ansible.builtin.lineinfile:
    line: "test_scan: false"
    regexp: "^test_scan: true"
    path: /etc/insights-client/malware-detection-config.yml

- name: Configure insight malware detection - 2
  ansible.builtin.lineinfile:
    line: "filesystem_scan_only: [/home]"
    regexp: "^filesystem_scan_only:"
    path: /etc/insights-client/malware-detection-config.yml
