---
- name: Install discovery installer
  ansible.builtin.package:
    name: "{{ rh_discovery_seapp_discovery_packages }}"
    state: present
    disable_gpg_check: yes

- name: Pull Red Hat discovery images
  containers.podman.podman_image:
    name: "{{ _discovery_image_ }}"
    username: "{{ rh_discovery_seapp_discovery_registry_username }}"
    password: "{{ rh_discovery_seapp_discovery_registry_password }}"
  loop: "{{ rh_discovery_seapp_discovery_images }}"
  loop_control:
    loop_var: _discovery_image_

- name: Run discovery-installer
  become: false
  become_user: lab-user
  ansible.builtin.expect:
    command: discovery-installer install
    responses:
      (?i)password: "{{ common_password }}"

# - name: Start discovery app as user service
#   become: false
#   command: systemctl --user start discovery-app


