---
- name: Enable repository
  ansible.builtin.command: >-
    subscription-manager repos
    --enable discovery-1-for-rhel-9-x86_64-rpms

- name: Install discovery installer
  ansible.builtin.package:
    name: discovery-installer
    state: present
  disable_gpg_check: yes

- name: Log in to Red Hat registry
  containers.podman.podman_login:
    registry: registry.redhat.io
    username: "{{ rh_discovery_seapp_discovery_registry_username }}"
    password: "{{ rh_discovery_seapp_discovery_registry_password }}"

- name: Run discovery-installer
  command: discovery-installer install

- name: Start discovery app as user service
  become: false
  command: systemctl --user start discovery-app
