---
- name: Enable repository
  ansible.builtin.shell: >-
    subscription-manager repos
    --enable discovery-1-for-rhel-9-x86_64-rpms

- name: Install discovery installer
  ansible.builtin.package:
    name: discovery-installer
    state: present
  disable_gpg_check: yes

  3 podman login registry.redhat.io
  4 discovery-installer install
  5 systemctl --user start discovery-app