---
- name: Read content of the file
  ansible.builtin.slurp:
    src: "/home/{{ lb1152_hol_node_config_lab_user }}/.ssh/authorized_keys"
  register: r_authorized_keys

- name: Copy authorized_keys
  ansible.builtin.lineinfile:
    path: /root/.ssh/authorized_keys
    insertafter: 'EOF'
    line: "{{ r_authorized_keys['content'] | b64decode }}"

- name: Copy SSH files
  ansible.builtin.copy:
    src: "/home/{{ lb1152_hol_node_config_lab_user }}/.ssh/{{ item }}"
    dest: /root/.ssh/
    remote_src: true
    owner: root
    group: root
  loop:
    - "{{ guid }}key.pub"
    - config

- name: Copy private ssh key
  ansible.builtin.copy:
    src: "/home/{{ lb1152_hol_node_config_lab_user }}/.ssh/{{ guid }}key.pem"
    dest: /root/.ssh/
    remote_src: true
    owner: root
    group: root
    mode: 0400

- name: Add root user in config
  ansible.builtin.lineinfile:
    regexp: ".*User ec2-user$"
    line: "  User root"
    path: /root/.ssh/config

- name: Remove entry from authorized_keys
  ansible.builtin.lineinfile:
    path: /root/.ssh/authorized_keys
    regexp: '^no-port-forwarding.*'
    state: absent
